runtime: python39  # Specify the Python runtime version you're using
entrypoint: gunicorn -b :$PORT app:main  # Entry point command for running your Flask application

instance_class: F2

automatic_scaling: 
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /static  # URL path for static files (CSS, JavaScript, images, etc.)
  static_dir: static  # Directory containing your static files

- url: /.*  # URL path for handling all other requests
  script: auto  # Use the built-in Flask development server
